modLoader="javafml"
loaderVersion="${loader_version}"
license="LGPL-3.0-or-later"
issueTrackerURL="https://github.com/TheIllusiveC4/Comforts/issues"
logoFile="comforts_icon.png"
logoBlur=false
[[mods]]
modId="comforts"
version="${version}"
displayName="Comforts"
displayURL="https://github.com/TheIllusiveC4/Comforts"
authors="C4"
description='''
Adds sleeping bags and hammocks for, respectively, portability and turning day to night, without setting new spawns.
Comes in 16 different colors!
'''
[[dependencies.comforts]]
    modId="forge"
    mandatory=true
    versionRange="${forge_version_range}"
    ordering="NONE"
    side="BOTH"
[[dependencies.comforts]]
    modId="minecraft"
    mandatory=true
    versionRange="${mc_version_range}"
    ordering="NONE"
    side="BOTH"
